# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExtTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(verbose_name='下单日期')),
                ('date', models.DateField(null=True, verbose_name='提取日期')),
                ('result', models.NullBooleanField(verbose_name='结论')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '1提取实验',
                'verbose_name_plural': '1提取实验',
            },
        ),
        migrations.CreateModel(
            name='LibTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(verbose_name='下单日期')),
                ('date', models.DateField(null=True, verbose_name='建库日期')),
                ('type', models.CharField(max_length=20, null=True, verbose_name='文库类型')),
                ('sample_code', models.CharField(max_length=20, null=True, verbose_name='样品编号')),
                ('lib_code', models.CharField(max_length=20, null=True, verbose_name='文库号')),
                ('index', models.CharField(max_length=20, null=True, verbose_name='Index')),
                ('length', models.PositiveIntegerField(null=True, verbose_name='文库大小bp')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='体积uL')),
                ('concentration', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='浓度ng/uL')),
                ('total', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='总量ng')),
                ('result', models.NullBooleanField(verbose_name='结论')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '3样品建库',
                'verbose_name_plural': '3样品建库',
            },
        ),
        migrations.CreateModel(
            name='QcTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(verbose_name='下单日期')),
                ('date', models.DateField(null=True, verbose_name='质检日期')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='体积uL')),
                ('concentration', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='浓度ng/uL')),
                ('total', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='总量ng')),
                ('result', models.IntegerField(choices=[(0, '待质检'), (1, '合格'), (2, '不合格（可风险建库）'), (3, '不合格（不可风险建库）')], null=True, verbose_name='结论')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '2样品质检',
                'verbose_name_plural': '2样品质检',
            },
        ),
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='样品类型')),
                ('species', models.CharField(max_length=20, verbose_name='物种')),
                ('name', models.CharField(max_length=50, verbose_name='样品名称')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='体积uL')),
                ('concentration', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='浓度ng/uL')),
                ('receive_date', models.DateField(verbose_name='收样日期')),
                ('check', models.NullBooleanField(verbose_name='样品核对')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '0样品管理',
                'verbose_name_plural': '0样品管理',
            },
        ),
        migrations.CreateModel(
            name='SeqTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
