# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=30, unique=True, verbose_name='合同号')),
                ('name', models.CharField(max_length=100, verbose_name='合同名')),
                ('type', models.IntegerField(choices=[(1, '16S/ITS'), (2, '宏基因组'), (3, '单菌'), (4, '转录组'), (5, '其它')], verbose_name='类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='单价')),
                ('range', models.IntegerField(blank=True, choices=[(1, '高于销售底价'), (2, '总监底价'), (3, '低于总监底价')], verbose_name='价格区间')),
                ('all_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总款额')),
                ('fis_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='首款额')),
                ('fis_date', models.DateField(blank=True, null=True, verbose_name='首款到款日')),
                ('fis_amount_in', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='已到首款额')),
                ('fin_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='尾款额')),
                ('fin_date', models.DateField(blank=True, null=True, verbose_name='尾款到款日')),
                ('fin_amount_in', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='已到尾款额')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='合同寄出日')),
                ('tracking_number', models.CharField(blank=True, max_length=15, verbose_name='快递单号')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='合同寄到日')),
                ('contract_file', models.FileField(blank=True, upload_to='uploads/%Y/%m', verbose_name='附件')),
                ('contacts', models.CharField(blank=True, max_length=15, verbose_name='合同联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('contact_note', models.TextField(blank=True, verbose_name='合同备注')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
            options={
                'verbose_name': '合同管理',
                'verbose_name_plural': '合同管理',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuingUnit', models.CharField(choices=[('sh', '上海锐翌'), ('hz', '杭州拓宏'), ('sd', '山东锐翌'), ('sz', '金锐生物')], default='sh', max_length=25, verbose_name='开票单位')),
                ('period', models.CharField(choices=[('FIS', '首款'), ('FIN', '尾款')], default='FIS', max_length=3, verbose_name='款期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='发票金额')),
                ('type', models.CharField(choices=[('CC', '普票'), ('SC', '专票')], default='CC', max_length=3, verbose_name='发票类型')),
                ('content', models.TextField(null=True, verbose_name='发票内容')),
                ('note', models.TextField(null=True, verbose_name='备注')),
                ('submit', models.NullBooleanField(verbose_name='提交开票')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '开票申请',
                'verbose_name_plural': '开票申请',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='发票抬头')),
                ('tariffItem', models.CharField(max_length=50, unique=True, verbose_name='税号')),
            ],
            options={
                'verbose_name': '发票抬头',
                'verbose_name_plural': '发票抬头',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.InvoiceTitle', verbose_name='发票抬头'),
        ),
    ]
