# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='到账金额')),
                ('date', models.DateField(verbose_name='到账日期')),
            ],
            options={
                'verbose_name': '进账管理',
                'verbose_name_plural': '进帐管理',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=12, unique=True, verbose_name='发票号码')),
                ('date', models.DateField(null=True, verbose_name='开票日期')),
                ('tracking_number', models.CharField(blank=True, max_length=15, verbose_name='快递单号')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='寄出日期')),
                ('income_date', models.DateField(null=True, verbose_name='到账日期')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='到账金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='开票税率')),
                ('invoice_file', models.FileField(null=True, upload_to='uploadsInvoice/%Y/%m', verbose_name='电子发票')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mm.Invoice', verbose_name='发票')),
            ],
            options={
                'verbose_name': '发票管理',
                'verbose_name_plural': '发票管理',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.Invoice', verbose_name='发票'),
        ),
    ]
