# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 08:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='客户姓名')),
                ('organization', models.CharField(max_length=20, verbose_name='单位（全称）')),
                ('department', models.CharField(max_length=20, verbose_name='院系/科室（全称）')),
                ('address', models.CharField(max_length=50, verbose_name='办公地址')),
                ('title', models.CharField(max_length=50, verbose_name='职务')),
                ('contact', models.PositiveIntegerField(verbose_name='联系方式')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('level', models.IntegerField(choices=[(1, '一般'), (2, '重要'), (3, '非常重要')], default=1, verbose_name='客户分级')),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='联络人')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
            },
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('project_type', models.IntegerField(choices=[(1, '16S/ITS'), (2, '宏基因组'), (3, '单菌'), (4, '转录组'), (5, '其它')], default=1, verbose_name='项目类型')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('closing_date', models.DateField(default=datetime.date(2018, 10, 16), verbose_name='预计成交时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预计成交价')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '意向管理',
                'verbose_name_plural': '意向管理',
            },
        ),
        migrations.CreateModel(
            name='IntentionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='进展/状态')),
                ('record_date', models.DateField(default=datetime.date(2018, 10, 16), verbose_name='跟进时间')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Intention', verbose_name='意向项目')),
            ],
            options={
                'verbose_name': '进展记录',
                'verbose_name_plural': '进展记录',
            },
        ),
    ]
