# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mm', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_cycle', models.PositiveIntegerField(verbose_name='项目分析周期')),
                ('ana_start_date', models.DateField(blank=True, null=True, verbose_name='分析开始日')),
                ('ana_end_date', models.DateField(blank=True, null=True, verbose_name='分析完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('ana_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分析实验员')),
            ],
            options={
                'verbose_name': '5分析任务下单',
                'verbose_name_plural': '5分析任务下单',
            },
        ),
        migrations.CreateModel(
            name='ExtSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_cycle', models.PositiveIntegerField(verbose_name='项目提取周期')),
                ('ext_date', models.DateField(blank=True, null=True, verbose_name='提取完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='提取任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('ext_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提取实验员')),
            ],
            options={
                'verbose_name': '1提取任务下单',
                'verbose_name_plural': '1提取任务下单',
            },
        ),
        migrations.CreateModel(
            name='LibSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_cycle', models.PositiveIntegerField(verbose_name='项目建库周期')),
                ('lib_date', models.DateField(blank=True, null=True, verbose_name='建库完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('lib_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建库实验员')),
            ],
            options={
                'verbose_name': '3建库任务下单',
                'verbose_name_plural': '3建库任务下单',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_number', models.CharField(max_length=100, verbose_name='子项目编号')),
                ('sub_project', models.CharField(max_length=40, verbose_name='子项目的名称')),
                ('project_start_time', models.DateField(max_length=20, verbose_name='立项时间')),
                ('receive_date', models.DateField(verbose_name='收到样品日期')),
                ('name', models.TextField(blank=True, max_length=100, verbose_name='项目注解')),
                ('is_ext', models.BooleanField(verbose_name='需提取')),
                ('is_lib', models.BooleanField(verbose_name='需建库')),
                ('is_seq', models.BooleanField(verbose_name='需测序')),
                ('is_ana', models.BooleanField(verbose_name='需分析')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('data_amount', models.CharField(max_length=10, verbose_name='数据要求')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pm/', verbose_name='提前启动图片')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='释放报告日')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='释放结果日')),
                ('data_date', models.DateField(blank=True, null=True, verbose_name='释放数据日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='合同节点')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='确认')),
                ('status', models.IntegerField(choices=[(0, '不能启动'), (2, '正常启动'), (1, '提前启动'), (3, '立项处理'), (4, '待首款'), (5, '提取中'), (6, '建库中'), (7, '测序中'), (8, '分析中'), (9, '待尾款'), (10, '尾款已到'), (11, '完成')], default=1, verbose_name='状态')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同号')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户姓名')),
                ('project_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目人员')),
                ('sample_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SampleInfoForm', verbose_name='样品类型')),
            ],
            options={
                'verbose_name': '0项目管理',
                'verbose_name_plural': '0项目管理',
            },
        ),
        migrations.CreateModel(
            name='SeqSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_cycle', models.PositiveIntegerField(verbose_name='项目测序周期')),
                ('seq_start_date', models.DateField(blank=True, null=True, verbose_name='测序开始日')),
                ('seq_end_date', models.DateField(blank=True, null=True, verbose_name='测序完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('sample', models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品')),
                ('seq_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='测序实验员')),
                ('seq_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Project', verbose_name='测序子项目编号')),
            ],
            options={
                'verbose_name': '4测序任务下单',
                'verbose_name_plural': '4测序任务下单',
            },
        ),
        migrations.AddField(
            model_name='libsubmit',
            name='lib_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Project', verbose_name='建库子项目编号'),
        ),
        migrations.AddField(
            model_name='libsubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='extsubmit',
            name='ext_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Project', verbose_name='提取子项目编号'),
        ),
        migrations.AddField(
            model_name='extsubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AddField(
            model_name='anasubmit',
            name='ana_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Project', verbose_name='分析子项目编号'),
        ),
        migrations.AddField(
            model_name='anasubmit',
            name='sample',
            field=models.ManyToManyField(to='lims.SampleInfo', verbose_name='样品'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('contract', 'name')]),
        ),
    ]
